#!/usr/bin/env node

const fs = require('fs-extra')
const { execSync } = require('child_process')

execSync('ts-patch install -s', { stdio: 'inherit' })

if (fs.pathExistsSync('tsconfig.build.json')) {
  execSync('tsc --build ./tsconfig.build.json', { stdio: 'inherit' })
} else {
  execSync('lerna run compile --parallel --include-filtered-dependencies --scope=@dumlj/tidy-cli', { stdio: 'inherit' })
  execSync('dumlj-tidy --exclude \"*/__template__\"', { stdio: 'inherit' })
}
