name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  npm:
    uses: dumlj/dumlj-workflows/.github/workflows/npm.workflow.yml@main
    secrets: inherit
