name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feat/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'fix/*'
      - 'ci/*'
      - 'perf/*'
      - 'docs/*'
      - 'style/*'
    tags-ignore:
      - '**'

jobs:
  npm:
    uses: dumlj/dumlj-workflows/.github/workflows/npm.workflow.yml@main
    secrets: inherit
